"""Pydantic schemas for request/response serialization."""

from datetime import datetime
from typing import Any
from pydantic import BaseModel, Field


# --- User schemas (NEW) ---

class UserCreate(BaseModel):
    """Request body for POST /api/users."""
    nombre: str = Field(..., min_length=1, max_length=100, strip_whitespace=True)


class UserResponse(BaseModel):
    """Response for user endpoints."""
    id: int
    nombre: str


# --- Project rename (NEW) ---

class ProjectRenameRequest(BaseModel):
    """Request body for PATCH project rename."""
    nombre_archivo: str = Field(..., min_length=1, max_length=200)


# --- Upload response ---

class ColumnSummary(BaseModel):
    """Column name and inferred type returned after upload."""
    name: str
    type: str


class TableSummary(BaseModel):
    """Summary of a parsed table returned after upload."""
    table_id: int
    sheet_name: str
    columns: list[ColumnSummary]
    row_count: int


class ProjectUploadResponse(BaseModel):
    """Response for POST /api/users/{user_id}/projects and upload endpoints."""
    user_id: int
    project_id: int
    tables: list[TableSummary]


# --- Table schemas ---

class ColumnOut(BaseModel):
    """A column with its id, name and type."""
    id: int
    name: str
    type: str


class RowOut(BaseModel):
    """A row with its id and JSONB data."""
    id: int
    data: dict[str, Any]


class SingleTableResponse(BaseModel):
    """Full table detail: columns + rows for a single table."""
    id: int
    sheet_name: str
    columns: list[ColumnOut]
    rows: list[RowOut]


class TableListResponse(BaseModel):
    """Response for GET table metadata list (no row data)."""
    tables: list['TableSummaryOut']


# --- Project listing & detail ---

class TableSummaryOut(BaseModel):
    """Lightweight table summary for project detail view."""
    id: int
    nombre_hoja: str
    row_count: int
    column_count: int


class ProjectSummary(BaseModel):
    """Project card data for the listing view."""
    id: int
    nombre_archivo: str
    fecha_creacion: datetime
    tabla_count: int


class ProjectListResponse(BaseModel):
    """Response for GET /api/users/{user_id}/projects."""
    projects: list[ProjectSummary]


class DashboardWidgetSchema(BaseModel):
    """Flexible widget schema — stored as dict for extensibility."""
    id: str
    type: str
    title: str


class DashboardConfigSchema(BaseModel):
    """Dashboard configuration with an array of widget dicts."""
    widgets: list[dict[str, Any]]
    generated_at: datetime | None = None


# ── AI Dashboard Generation: Widget Validation Schemas ──


class KpiWidgetSchema(BaseModel):
    """Strict schema for KPI widgets generated by AI."""
    id: str
    type: str = "kpi"
    label: str
    value: float
    format: str
    prefix: str | None = None
    suffix: str | None = None
    trend: str | None = None
    trendValue: str | None = None


class ChartWidgetSchema(BaseModel):
    """Strict schema for chart widgets generated by AI."""
    id: str
    type: str = "chart"
    chartType: str
    variant: str | None = None
    title: str
    x: str | None = None
    y: str | None = None
    data: list[dict[str, Any]] | None = None
    series: list[dict[str, Any]] | None = None
    orientation: str | None = None
    areaStyle: dict[str, Any] | None = None
    colorPalette: list[str] = []
    x_label: str | None = None
    y_label: str | None = None


class InsightWidgetSchema(BaseModel):
    """Strict schema for insight widgets generated by AI."""
    id: str
    type: str = "insight"
    emoji: str
    content: str
    severity: str


class GenerateDashboardResponse(BaseModel):
    """Response for POST /generate-dashboard."""
    widgets: list[dict[str, Any]]
    generated_at: datetime
    resumen_ejecutivo: str | None = None
    action_message: str | None = None


class IterateDashboardRequest(BaseModel):
    """Request body for POST /users/{user_id}/projects/{project_id}/chat."""
    prompt: str = Field(..., min_length=1, strip_whitespace=True)
    current_dashboard: dict[str, Any]


class ProjectDetail(BaseModel):
    """Full project detail with tables for the project detail view."""
    id: int
    nombre_archivo: str
    fecha_creacion: datetime
    tables: list[TableSummaryOut]
    dashboard_config: DashboardConfigSchema | None = None
